version: '3.8'

services:
  app:
    image: my-app-frontend-dev
  server:
    image: my-app-backend-dev
    build:
      context: ./blog-refactor-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./blog-refactor-backend:/usr/src/server
    env_file: ./blog-refactor-backend/.env
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - 3003:80
    container_name: reverse-proxy
    depends_on:
      - server
  