version: '3.8'

services:
  app:
    image: my-app-frontend-prod
    build: ./blog-refactor-frontend
    volumes:
      - static-build:/usr/src/blog-refactor-frontend/dist
  server:
    image: my-app-backend-prod
    build: ./blog-refactor-backend
    volumes:
      - static-build:/usr/src/blog-refactor-frontend/dist
    environment:
      - MONGO_DOCKER_URL=mongodb://the_username:the_password@mongo:27017/the_database
    env_file: ./blog-refactor-backend/.env
    depends_on:
      - app
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./blog-refactor-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./blog-refactor-backend/mongo_data:/data/db
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - 3001:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
      - mongo

# notice how the volume is used to serve the static build
volumes:
  static-build: