version: '3.8'

services:
  app:
    image: todo-frontend-prod
    build: ./todo-frontend
    volumes:
      - ./todo-frontend/:/usr/src/app
  server:
    image: todo-backend-prod
    build: ./todo-backend
    volumes:
      - ./todo-backend/:/usr/src/server
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
  mongo: # this is for containerizing the mongo DB
    image: mongo
    ports: 
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db # local storage of data
  redis:
    image: redis
    ports:
      - 6379
    command: ['redis-server', '--appendonly', 'yes'] # Override CMD to persist state
    volumes:
      - ./todo-backend/redis_data:/data #volume for storage
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
      - mongo
      - redis