### GET request for all blogs
GET http://localhost:3001/api/blogs
Content-Type: application/json

### POST request for new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Jane",
  "title": "Jane Blog",
  "url": "jane.org",
  "likes": 35
}

### PUT request to update the number of likes
PUT http://localhost:3001/api/blogs/4
Content-Type: application/json

{
  "likes": 15
}


### DELETE request for blog
DELETE http://localhost:3001/api/blogs/12

### GET request for all users
GET http://localhost:3001/api/users

### POST request to create new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Sophia Banks",
  "username": "spb1122@gmail.org",
  "password": "example"
}

### PUT request to change a username
PUT http://localhost:3001/api/users/jonBilliams
Content-Type: application/json

{
  "newUsername": "goldrushSupreme"
}

### POST request to log in 
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "goldrushSupreme",
  "password": "exampl"
}
