POST http://localhost:4000/graphql
Content-Type: application/json

{
    "query" : "query { allAuthors {name born bookCount} }"
}

###
POST http://localhost:4000/graphql
Content-Type: application/json

{
    "query" : "query { allBooks {title author} }"
}


