POST http://localhost:4000/graphql
Content-Type: application/json

{
    "query" : "query { allAuthors {name born bookCount} }"
}

###
POST http://localhost:4000/graphql
Content-Type: application/json

{
    "query" : "query { allBooks {title} }"
}

###
POST http://localhost:4000/graphql
Content-Type: application/json

{
    "query" : "query { authorCount }"
}

### NOTICE THAT THE ENTIRE QUERY HAS TO BE ON A SINGLE LINE!! OTHERWISE IT WON'T WORK
POST http://localhost:4000/graphql
Content-Type: application/json
Authorization: Bearer 

{
    "operationName": "setBirthyear",
    "variables": {
        "name": "Alan Anderson",
        "setBornTo": 1922
    },
    "query": "mutation setBirthyear($name: String!, $setBornTo: Int!) {editAuthor(name: $name, setBornTo: $setBornTo) {name born bookCount}}"

}


### This won't work, bc it's not all on one line.
POST http://localhost:4000/graphql
Content-Type: application/json
Authorization: Bearer 

{
    "query" : "mutation setBirthyear($name: String!, $setBornTo: Int!) {
        editAuthor(name: $name, setBornTo: $setBornTo) {
            name
            born
            bookCount
        }
    }",
    "operation name" : "setBirthyear",
    "variables" : {
        "name": "Alan Anderson",
        "setBornTo": 1920
    }
}