name: Deployment pipeline (part 11)

on:
  push:
    branches:
      - main #only deploy for pushes to part_11 on main branch

jobs:
  deployment_pipeline_part_11:
    runs-on: ubuntu-20.04
    steps:
      - uses: echo "$github.repository"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.17' #version in render production environment