name: Deployment pipeline (part 11)

on:
  push:
    branches:
      - main #only deploy for pushes to part_11 on main branch

jobs:
  deployment_pipeline_part_11:
    runs-on: ubuntu-20.04
    steps:
      - name: Check repository
        env:
          FOUND_REPO: $github.repository
        run: echo "$FOUND_REPO"