name: Deployment pipeline (part 11)

on:
  push:
    branches:
      - main #only deploy for pushes to part_11 on main branch

jobs:
  deployment_pipeline_part_11:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: | 
            part_11
      - name: check working directory
        run: cd part_11 && ls -a