name: Deployment pipeline (part 11)

on:
  push:
    branches:
      - main #only deploy for pushes to part_11 on main branch

jobs:
  deployment_pipeline_part_11:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |  #only checkout part_11 folder
            part_11
      - uses: actions/setup-node@v3
        with:
          node-version: '14.17' #same node version as in render production environment
      - name: Install frontend dependencies
        run: cd part_11/blog-refactor-frontend && npm install
      - name: Install backend dependencies
        run: cd part_11/blog-refactor-backend && npm install
      - name: check working directory in subsequent step
        run: ls -a