name: Deployment pipeline (part 11)

on:
  push:
    branches:
      - 'main/part_11' #only deploy for pushes to part_11 on main branch

jobs:
  deployment_pipeline_part_11:
    runs-on: ubuntu-20.04
    env: #environmental variables: from github secrets to this environment. NOTICE THIS!!!
      SECRET: ${{ secrets.SECRET}}
      TOKEN: ${{ secrets.TOKEN }}
      RANDY_HASH: ${{ secrets.RANDY_HASH }}
      MONGODB_PW: ${{ secrets.MONGODB_PW}}
      MONGODB_URI: ${{ secrets.MONGODB_URI}}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI}}
      PORT: ${{ secrets.PORT}}
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |  #only checkout part_11 folder
            part_11
      - uses: actions/setup-node@v3
        with:
          node-version: '14.17' #same node version as in render production environment
      
      - name: Install frontend dependencies
        run: cd part_11/blog-refactor-frontend && npm install
      - name: Install backend dependencies
        run: cd part_11/blog-refactor-backend && npm install
      - name: Check (frontend) style
        run: cd part_11/blog-refactor-frontend && npm run lint
      - name: Run (backend) integration tests
        run: cd part_11/blog-refactor-backend && npm run test